#!/bin/bash

# Archlinux repository rebuild script
# For those, who creates own repo with packages from aur
# Helps keep repository up-to-date
#
# (c) 2010-2015, Stanislav N. aka pztrn. No rights reserved.
# Licensed under GNU General Public License v2 or higher.
# Dual licensed under beerware license. Read LICENSE
# for more information.
#
# Thanks to Russian Archlinux Community (http://archlinux.org.ru)
# for help and suggestions
#
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


################################################### Variables ##########
PKGNAME=1
RR_PATH=$(pwd $0)
LOG_LINES_COUNT_ON_EXIT=10
########################################################################

################################################### CONFIGURATION ######
. ~/.config/reporebuild.conf
########################################################################

################################################### Includes ###########
source "${RR_PATH}/lib/builder.lib.sh"
source "${RR_PATH}/lib/common.lib.sh"
source "${RR_PATH}/lib/config.lib.sh"
source "${RR_PATH}/lib/downloader.lib.sh"
source "${RR_PATH}/lib/log.lib.sh"
########################################################################

configcheck
tmpdir

function execute_action() {
    local action=$1
    shift
    local params=$@
    if [ -f "${RR_PATH}/actions/${action}.action.sh" ]; then
        source "${RR_PATH}/actions/${action}.action.sh"
        func_here=`declare -F ${action}_main`
        if [ $func_here ]; then
            log 1 "NORMAL" "Executing action '${action}'..."
            function="${action}_main"
            ${function} $@
        fi
    else
        log 0 "ERROR" "Action '${action}' does not exist."
        exit 1
    fi
}

case "$1" in
*)
    execute_action $@
    ;;
esac

exit
########################################################################
